dist: trusty
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - coreutils
     - g++-4.8
     - gdb

language: node_js

node_js:
  - "6"
  - "5"
  - "4"

install:
  - make all

script:
- make test
