# We actually depend on this being the generic image
language: generic

cache:
  directories:
  - ${HOME}/.ccache

sudo: false

env:
  global:
   - CCACHE_TEMPDIR=/tmp/.ccache-temp
   - CCACHE_COMPRESS=1
   - CASHER_TIME_OUT=1000
   - CC="clang"
   - CXX="clang++"

addons_default: &apt_packages
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    # note: libstdc++-5-dev is required by clang-3.8 for its headers (clang-3.8 is installed by mason on linux)
    packages: [ 'libstdc++-5-dev', 'zlib1g-dev', 'make', 'apport', 'gdb' ]

script_default: &build_and_test
    - make test

matrix:
  include:
    # Linux
    - os: linux
      env: NODE="4" TARGET=Release
      addons: *apt_packages
      script: *build_and_test
    - os: linux
      env: NODE="4" TARGET=Debug NPM_FLAGS="--debug"
      addons: *apt_packages
      script: *build_and_test
    - os: linux
      env: NODE="6" TARGET=Release
      addons: *apt_packages
      script: *build_and_test
    - os: linux
      env: NODE="6" TARGET=Debug NPM_FLAGS="--debug"
      addons: *apt_packages
      script: *build_and_test
